name: Executar Notebook
name: Executar Notebook com Papermill

on:
  push:
    paths:
      - '**.ipynb'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install papermill

      - name: Executar notebook com Papermill
        run: |
          papermill associacao_por_proximidade.ipynb associacao_por_proximidade_output.ipynb
